### ISSUE TITLE
Add find command (for tags)

### ISSUE THREAD

**Issue by Eugenetanwl3881** [AY2223S1-CS2103T-W16-2/tp#21] opened 2022-09-23 09:25 UTC
This is a new command.
Users will be able to search for tags and view the items with the tags.

It requires the inventory item model and the tag model to be implemented first.

Command format: tag find TAG_NAME

Some of the implementation will be similar to #20

**Comment by Ferusel** [comment] 2022-10-14 04:33
NOTE: Duplicate of #18. Will close this.

**Closed by Ferusel** 2022-10-14 04:33 UTC
Labels: type.story
